name = "gemini-2"
main = "src/worker.js"
workers_dev = true
compatibility_date = "2025-07-25"

[observability]
enabled = true

[vars]
CORS_ORIGIN = "https://plus62store-vite.vercel.app"
CORS_ORIGIN_LOCAL = "http://localhost:5500"

[[kv_namespaces]]
binding = "CHAT_HISTORY_KV"
id = "id_kv_kamu"

[[kv_namespaces]]
binding = "GEMINI_KEY_QUOTA_KV"
id = "id_kv_kamu"

# Tambahkan AI binding
[ai]
binding = "AI"