name = "gemini-2"
main = "src/worker.js"
workers_dev = true
compatibility_date = "2025-07-25"

[observability]
enabled = true

[vars]
CORS_ORIGIN = "https://plus62store.vercel.app"
CORS_ORIGIN_LOCAL = "http://localhost:5500"

[[kv_namespaces]]
binding = "CHAT_HISTORY_KV"
id = "941a07f16b68499f889d332b6c874daf"

[[kv_namespaces]]
binding = "GEMINI_KEY_QUOTA_KV"
id = "ced80c3244ab49458442be3eabe2535e"

# Tambahkan AI binding
[ai]
binding = "AI"